services:
  db:
    image: postgres
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
  service:
    container_name: service
    image: service
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres?schema=public
    depends_on:
      - db
    

volumes:
 pg_data:

